// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://botnifnuxvicmmlanzcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvdG5pZm51eHZpY21tbGFuemNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjA4OTQsImV4cCI6MjA1OTgzNjg5NH0.-BZw0goNUUlGQLC_J-Oxo9LPmIVkizFocX4JwyXVJ7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);